# circleci config



jobs:
  test-a:
    - run: |
        export GRABL_USERNAME=$CIRCLE_USERNAME
        export GRABL_TOKEN=$CIRCLE_TOKEN
        bazel run @graknlabs_build_tools//build/correctness:start # this job expects $CIRCLE_JOB_NAME $CIRCLE_ORG, $CIRCLE_REPO, $CIRCLE_JOB_ID
    - onsuccess: |
        export GRABL_USERNAME=$CIRCLE_USERNAME
        export GRABL_TOKEN=$CIRCLE_TOKEN
        bazel run @graknlabs_build_tools//build/correctness:success # this job expects $CIRCLE_JOB_NAME $CIRCLE_ORG, $CIRCLE_REPO, $CIRCLE_JOB_ID
    - onerror: |
        export GRABL_USERNAME=$CIRCLE_USERNAME
        export GRABL_TOKEN=$CIRCLE_TOKEN
        bazel run @graknlabs_build_tools//build/correctness:error # this job expects $CIRCLE_JOB_NAME $CIRCLE_ORG, $CIRCLE_REPO, $CIRCLE_JOB_ID

  performance-small:
    run: |
      bazel test //test/performance:small--
        --grakn-address $GRABL_GRAKN_ADDRESS
        --org $GRABL_ORG
        --repo $GRABL_REPO
        --commit $GRABL_COMMIT
        --username $GRABL_USERNAME
        --token $GRABL_TOKEN

  grabl-correctness-completed:
    run: |
      export GRABL_USERNAME=$CIRCLE_USERNAME
      export GRABL_TOKEN=$CIRCLE_TOKEN
      bazel run @graknlabs_build_tools//build/correctness:completed -- --org $CIRCLE_ORG --repo $CIRCLE_REPO

  deploy-github:
    - run: |
        export GRABL_USERNAME=$CIRCLE_USERNAME
        export GRABL_TOKEN=$CIRCLE_TOKEN
        bazel run @graknlabs_build_tools//release/deployment:start # this job expects $CIRCLE_JOB_NAME $CIRCLE_ORG, $CIRCLE_REPO, $CIRCLE_JOB_ID
    - run: |
        bazel run //:deploy-github
    - onsuccess: |
        export GRABL_USERNAME=$CIRCLE_USERNAME
        export GRABL_TOKEN=$CIRCLE_TOKEN
        bazel run @graknlabs_build_tools//release/deployment:success # this job expects $CIRCLE_JOB_NAME $CIRCLE_ORG, $CIRCLE_REPO, $CIRCLE_JOB_ID
    - onerror: |
        export GRABL_USERNAME=$CIRCLE_USERNAME
        export GRABL_TOKEN=$CIRCLE_TOKEN
        bazel run @graknlabs_build_tools//release/deployment:error # this job expects $CIRCLE_JOB_NAME $CIRCLE_ORG, $CIRCLE_REPO, $CIRCLE_JOB_ID
  grabl-release-completed:
    - run: |
        export GRABL_USERNAME=$CIRCLE_USERNAME
        export GRABL_TOKEN=$CIRCLE_TOKEN
        bazel run @graknlabs_build_tools//release/deployment:success # this job expects $CIRCLE_ORG, $CIRCLE_REPO, $CIRCLE_JOB_ID

workflows:
  grakn:
    jobs:
      - test-a
      - performance-small
      - grabl-correctness-completed:
          requires:
            - test-a
            - performance-small

  grakn-release:
    jobs:
      - deploy-github
      - grabl-release-completed:
          requires:
            - deploy-a
